---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes
    force_apt_get: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install nodejs"
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update-cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

name: 'exporting env'
  become: yes
  shell: |
    export NODE_ENV=production 
    export VERSION=1 
    export TYPEORM_CONNECTION=postgres 
    export TYPEORM_MIGRATIONS_DIR=./src/migrations 
    export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
    export TYPEORM_MIGRATIONS=./src/migrations/*.ts 
    export TYPEORM_HOST=project3-database.cp87tcdlxnru.us-east-1.rds.amazonaws.com
    export TYPEORM_PORT=5432
    export TYPEORM_USERNAME=postgres
    export TYPEORM_PASSWORD=22121975
    export TYPEORM_DATABASE=postgres 
