---
- name: "ceating ~/wed directory"
  file: 
    path: ~/web
    state: directory

- name: "Extract backend files"
  unarchive: 
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: "install npm packages"
  shell: |
    cd ~/web
    npm install

 - name: Remove all apps from PM2 manager
    command: pm2 delete all
    ignore_errors: yes

- name: "configure pm2 to start as service"
  become: true 
  shell: |
    pm2 startup
    env PATH=$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu

- name: Start the PM2 apps
  shell: |
    cd ~/web 
    pm2 start npm --name=web -- start  

- name: 'Save PM2 configuration'
  become: yes
  shell: |
    pm2 save
  register: execute_node


- name: "print execute_node"
  debug: 
    msg: "{{execute_node.stdout_lines}}"


    